// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AccordionController from "./accordion_controller"
application.register("accordion", AccordionController)

import BlockFormController from "./block_form_controller"
application.register("block-form", BlockFormController)

import CategorySelectorController from "./category_selector_controller"
application.register("category-selector", CategorySelectorController)

import TagSelectorController from "./tag_selector_controller"
application.register("tag-selector", TagSelectorController)

import FormValidationController from "./form_validation_controller"
application.register("form-validation", FormValidationController)

import GoogleMapController from "./google_map_controller"
application.register("google-map", GoogleMapController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import CandlestickController from "./candlestick_controller"
application.register("candlestick", CandlestickController)

import MenuItemsController from "./menu_items_controller"
application.register("menu-items", MenuItemsController)

import BingoSelectorController from "./bingo_selector_controller"
application.register("bingo-selector", BingoSelectorController)

import SettingsFormController from "./settings_form_controller"
application.register("settings-form", SettingsFormController)

import SlideshowController from "./slideshow_controller"
application.register("slideshow", SlideshowController)

import OverlayNotificationController from "./overlay_notification_controller"
application.register("overlay-notification", OverlayNotificationController)

import OverlayRefreshController  from "./overlay_refresh_controller"
application.register("overlay-refresh", OverlayRefreshController )

import LightboxController from "./lightbox_controller"
application.register("lightbox", LightboxController)

import GalleryController from "./gallery_controller"
application.register("gallery", GalleryController)

import TrixController from "./trix_controller"
application.register("trix", TrixController)